#pragma once

#include "layouts.h"

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_SNAKE
#    define RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_CHRISTMAS
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define RGBLIGHT_EFFECT_RGB_TEST
#    define RGBLIGHT_EFFECT_ALTERNATING
#    define RGBLIGHT_EFFECT_TWINKLE
#    define RGBLIGHT_HUE_STEP 8
#    define RGBLIGHT_SAT_STEP 8
#    define RGBLIGHT_VAL_STEP 8
#    ifndef RGBLIGHT_LIMIT_VAL
#    	define RGBLIGHT_LIMIT_VAL 150
#    endif
#endif

#ifdef COMBO_ENABLE
#    define COMBO_TERM 20
#    define COMBO_ONLY_FROM_LAYER 0
#    define COMBO_SHOULD_TRIGGER
#    define COMBO_COUNT 6
#endif

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define ENABLE_COMPILE_KEYCODE
#define CONSOLE_ENABLE = no

#define ONESHOT_TAP_TOGGLE 2
